### ISSUE TITLE
Non-existing -root directory crashes kellner

### ISSUE THREAD

**Issue by hsychla** [carosio/kellner#8]
If the directory given as `-root=` does not exist, kellner crashes:

```
Dec 16 12:55:28 vmware systemd[1]: Started Kellner - fast ad hoc serving of packages.
Dec 16 12:55:28 vmware systemd[1]: Starting Kellner - fast ad hoc serving of packages...
Dec 16 12:55:28 vmware kellner[482]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 16 12:55:28 vmware kellner[482]: [signal 0xb code=0x1 addr=0x20 pc=0x411769]
Dec 16 12:55:28 vmware kellner[482]: goroutine 1 [running]:
Dec 16 12:55:28 vmware kellner[482]: main.func·006(0x7fffe6a80f77, 0x8, 0x0, 0x0, 0x7f347c194230, 0xc20800b860, 0x0, 0x0)
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/work/core2-64-tposs-linux/kellner/0.5.2-r0/kellner/scan.go:28 +0x99
Dec 16 12:55:28 vmware kellner[482]: path/filepath.Walk(0x7fffe6a80f77, 0x8, 0xc208097d10, 0x0, 0x0)
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/sysroots/x86_64-linux/usr/lib/x86_64-tposs-linux/go/src/path/filepath/path.go:392 +0xb6
Dec 16 12:55:28 vmware kellner[482]: main.scanRoot(0x7fffe6a80f77, 0x8, 0x760790, 0x5, 0x4, 0x1, 0x7fbdb8)
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/work/core2-64-tposs-linux/kellner/0.5.2-r0/kellner/scan.go:96 +0x8b
Dec 16 12:55:28 vmware kellner[482]: main.main()
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/work/core2-64-tposs-linux/kellner/0.5.2-r0/kellner/main.go:109 +0xd53
Dec 16 12:55:28 vmware kellner[482]: goroutine 17 [syscall, locked to thread]:
Dec 16 12:55:28 vmware kellner[482]: runtime.goexit()
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/sysroots/x86_64-linux/usr/lib/x86_64-tposs-linux/go/src/runtime/asm_amd64.s:2232 +0x1
Dec 16 12:55:28 vmware kellner[482]: goroutine 5 [syscall]:
Dec 16 12:55:28 vmware kellner[482]: os/signal.loop()
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/sysroots/x86_64-linux/usr/lib/x86_64-tposs-linux/go/src/os/signal/signal_unix.go:21 +0x1f
Dec 16 12:55:28 vmware kellner[482]: created by os/signal.init·1
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/sysroots/x86_64-linux/usr/lib/x86_64-tposs-linux/go/src/os/signal/signal_unix.go:27 +0x35
Dec 16 12:55:28 vmware kellner[482]: goroutine 7 [runnable]:
Dec 16 12:55:28 vmware kellner[482]: main.func·004()
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/work/core2-64-tposs-linux/kellner/0.5.2-r0/kellner/logging.go:39
Dec 16 12:55:28 vmware kellner[482]: created by main.setupLogging
Dec 16 12:55:28 vmware kellner[482]: /REDO/build/tmp/work/core2-64-tposs-linux/kellner/0.5.2-r0/kellner/logging.go:52 +0x492
```

**Comment by mgumz** [comment]
should be fixed via f912dfa03b285897104a4d0b44086a35e89ec9ef
